services:
  - type: web
    name: telegram-rss-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DATABASE_URL
        value: postgresql://bot_user:1111@localhost/telegram_rss_bot
      - key: BOT_TOKEN
        value: your_bot_token_here